# Generated by Django 6.0 on 2025-12-30 04:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='active_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
